// Generates migrations/d1/0002_seed.sql from the SPA's source-of-truth
// TypeScript data files. Re-run any time src/data/categories.ts or
// src/data/saints.ts or src/data/artist-tags.ts changes.

import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { categories } from '../src/data/categories';
import { saints } from '../src/data/saints';
import { DIOCESE_COORDS, ORDERS } from '../src/data/artist-tags';

function esc(s: unknown): string {
  if (s == null) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

const lines: string[] = [];
lines.push('-- Ars Sacra · D1 reference data seed');
lines.push('-- Generated by scripts/gen-d1-seed.ts. DO NOT EDIT BY HAND.');
lines.push('');

// Categories
for (let i = 0; i < categories.length; i++) {
  const c = categories[i];
  lines.push(
    `INSERT OR REPLACE INTO categories (slug, name, short_name, blurb, palette_from, palette_to, sort_order) VALUES (` +
      [
        esc(c.slug),
        esc(c.name),
        esc(c.shortName),
        esc(c.blurb ?? null),
        esc(c.paletteFrom ?? null),
        esc(c.paletteTo ?? null),
        i,
      ].join(', ') +
      ');',
  );
}
lines.push('');

// Saints
for (const s of saints) {
  lines.push(
    `INSERT OR REPLACE INTO saints (slug, name, also, feast_month, feast_day, patron_of, blurb, palette_from, palette_to) VALUES (` +
      [
        esc(s.slug),
        esc(s.name),
        esc(JSON.stringify(s.also ?? [])),
        s.feastMonth,
        s.feastDay,
        esc(JSON.stringify(s.patronOf ?? [])),
        esc(s.blurb ?? null),
        esc(s.paletteFrom ?? null),
        esc(s.paletteTo ?? null),
      ].join(', ') +
      ');',
  );
}
lines.push('');

// Dioceses
for (const [name, coords] of Object.entries(DIOCESE_COORDS)) {
  const [longitude, latitude] = coords as [number, number];
  lines.push(
    `INSERT OR REPLACE INTO dioceses (name, longitude, latitude) VALUES (${esc(name)}, ${longitude}, ${latitude});`,
  );
}
lines.push('');

// Religious orders
for (const o of ORDERS) {
  lines.push(
    `INSERT OR REPLACE INTO religious_orders (slug, name, charism, palette_from, palette_to) VALUES (` +
      [
        esc(o.slug),
        esc(o.name),
        esc(o.charism ?? null),
        esc(o.paletteFrom ?? null),
        esc(o.paletteTo ?? null),
      ].join(', ') +
      ');',
  );
}

const OUT = resolve('migrations/d1/0002_seed.sql');
await writeFile(OUT, lines.join('\n') + '\n');
console.log(`✓ wrote ${lines.length} lines → ${OUT}`);
console.log(`  ${categories.length} categories, ${saints.length} saints, ${Object.keys(DIOCESE_COORDS).length} dioceses, ${ORDERS.length} orders`);
