// Generates migrations/d1/0003_seed_artists.sql from the TypeScript
// artist data. Run with: npx tsx scripts/gen-d1-artists.ts

import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { artists } from '../src/data/artists';
import { ARTIST_TAGS } from '../src/data/artist-tags';

const OUT = resolve('migrations/d1/0003_seed_artists.sql');

function esc(s: unknown): string {
  if (s == null) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

const lines: string[] = [];
lines.push('-- Ars Sacra · seed artist directory');
lines.push('-- Generated by scripts/gen-d1-artists.ts from src/data/artists.ts.');
lines.push('-- Re-run after any artist data change.');
lines.push('');

for (const a of artists) {
  const id = `art_${a.slug.replace(/-/g, '_')}`;
  const tag = (ARTIST_TAGS as Record<string, { saintSlugs: string[]; diocese?: string; order?: string }>)[a.slug] ?? {
    saintSlugs: [],
  };
  const bioJson = JSON.stringify(a.bio ?? []);

  lines.push(
    `INSERT OR REPLACE INTO artists (id, slug, honorific, name, city, region, bio, portrait_from, portrait_to, accepting_commissions, years_practicing, starting_at, custom_pricing, diocese_name, order_slug, vocation_statement, patron) VALUES (` +
      [
        esc(id),
        esc(a.slug),
        esc(a.honorific),
        esc(a.name),
        esc(a.city),
        esc(a.region),
        esc(bioJson),
        esc(a.portraitFrom),
        esc(a.portraitTo),
        a.acceptingCommissions ? 1 : 0,
        a.yearsPracticing ?? 0,
        a.startingAt ?? 0,
        a.customPricing ? 1 : 0,
        esc(tag.diocese ?? null),
        esc(tag.order ?? null),
        esc(a.vocationStatement),
        esc(a.patron),
      ].join(', ') +
      ');',
  );

  for (const cat of a.categories ?? []) {
    lines.push(
      `INSERT OR REPLACE INTO artist_categories (artist_id, category_slug) VALUES (${esc(id)}, ${esc(cat)});`,
    );
  }
  for (const s of tag.saintSlugs ?? []) {
    lines.push(
      `INSERT OR REPLACE INTO artist_saints (artist_id, saint_slug) VALUES (${esc(id)}, ${esc(s)});`,
    );
  }
  for (let i = 0; i < (a.tiers ?? []).length; i++) {
    const t = a.tiers[i];
    lines.push(
      `INSERT OR REPLACE INTO artist_tiers (id, artist_id, tier_id, name, description, starting_at, turnaround_weeks_min, turnaround_weeks_max, sort_order) VALUES (` +
        [
          esc(`tier_${a.slug}_${t.id}`),
          esc(id),
          esc(t.id),
          esc(t.name),
          esc(t.description),
          t.startingAt ?? 0,
          t.turnaroundWeeks?.[0] ?? 6,
          t.turnaroundWeeks?.[1] ?? 12,
          i,
        ].join(', ') +
        ');',
    );
  }
  for (let i = 0; i < (a.works ?? []).length; i++) {
    const w = a.works[i];
    lines.push(
      `INSERT OR REPLACE INTO artworks (id, artist_id, title, year, medium, dimensions, caption, pattern, palette_from, palette_to, sort_order) VALUES (` +
        [
          esc(`work_${a.slug}_${i}`),
          esc(id),
          esc(w.title),
          w.year ?? 'NULL',
          esc(w.medium),
          esc(w.dimensions),
          esc(w.caption),
          esc(w.pattern),
          esc(w.paletteFrom),
          esc(w.paletteTo),
          i,
        ].join(', ') +
        ');',
    );
  }
  lines.push('');
}

await writeFile(OUT, lines.join('\n'));
console.log(`✓ wrote ${lines.length} lines → ${OUT}`);
console.log(`  ${artists.length} artists seeded`);
