// Generated by scripts/import-discovery.mjs from the Perplexity
// research dump. These are NOT Locavit members — they are publicly-
// researched Catholic sacred artists and religious-order workshops
// surfaced on /directory and /map so commissioners can discover them.
//
// Regenerate: drop a fresh CSV at scripts/.cache/discovery-source.md
// and run `node scripts/import-discovery.mjs`.

export interface DirectoryEntry {
  id: string;
  name: string;
  type: 'Individual' | 'Lay atelier' | 'Religious order workshop' | 'Monastery workshop';
  order: string | null;
  city: string | null;
  region: string | null;
  country: string;
  disciplines: string[];
  website: string | null;
  email: string | null;
  social: string | null;
  notableWorks: string[];
  training: string | null;
  endorser: string | null;
  activeSince: number | null;
  sourceUrl: string | null;
  notes: string | null;
  lat: number | null;
  lon: number | null;
}

export const DIRECTORY_ENTRIES: DirectoryEntry[] = [
  {
    "id": "clear-creek-abbey-wood-workshop",
    "name": "Clear Creek Abbey Wood Workshop",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Hulbert",
    "region": "Oklahoma",
    "country": "USA",
    "disciplines": [
      "Wood carving",
      "Architectural ornament"
    ],
    "website": "https://www.clearcreekmonks.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Reredos for St. Francis de Sales Oratory Sulphur LA (2022)",
      "tympanum for abbey church"
    ],
    "training": "Monastic formation; Br. Bernard Marie Dunne OSB (woodcarver)",
    "endorser": "Diocese of Tulsa; Institute of Christ the King",
    "activeSince": 2022,
    "sourceUrl": "https://www.lcdiocese.org/3-news/3335-work-and-pray-oratory-installs-reredos-above-altar",
    "notes": "Active workshop 2022–2025 confirmed; individual friar Br. Bernard Marie Dunne OSB is primary carver",
    "lat": 35.93,
    "lon": -95.13
  },
  {
    "id": "silverstream-priory",
    "name": "Silverstream Priory",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Stamullen",
    "region": "County Meath",
    "country": "Ireland",
    "disciplines": [
      "Illumination",
      "Calligraphy",
      "Watercolor"
    ],
    "website": "https://www.cenacleosb.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Watercolor Christmas card images",
      "illuminated items via Cenacle Press"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Diocese of Meath",
    "activeSince": 2019,
    "sourceUrl": "https://www.newliturgicalmovement.org/2019/11/christmas-cards-and-other-items-from.html",
    "notes": "Small community 15 members; art output via gift shop cenaclepress.com; no named individual artist publicly confirmed",
    "lat": 53.62,
    "lon": -6.27
  },
  {
    "id": "christ-in-the-desert-abbey",
    "name": "Christ in the Desert Abbey",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Abiquiu",
    "region": "New Mexico",
    "country": "USA",
    "disciplines": [
      "Illumination",
      "Ceramics",
      "Liturgical bookbinding"
    ],
    "website": "https://www.christdesert.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Abbey church",
      "art gallery",
      "gift shop active 2024–2026"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Archdiocese of Santa Fe",
    "activeSince": 2024,
    "sourceUrl": "https://christdesert.org",
    "notes": "Art gallery confirmed open 2024; no named resident artist-monk identified publicly",
    "lat": 36.21,
    "lon": -106.31
  },
  {
    "id": "mount-angel-abbey",
    "name": "Mount Angel Abbey",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Mount Angel",
    "region": "Oregon",
    "country": "USA",
    "disciplines": [
      "Iconography",
      "Illumination"
    ],
    "website": "https://www.mountangelabbey.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Resurrection icon by Br. Claude Lane OSB",
      "hosts Classical Iconography Institute annual retreat 2024"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Archdiocese of Portland",
    "activeSince": 2019,
    "sourceUrl": "https://www.mountangelabbey.org/monastery/art/",
    "notes": "Br. Claude Lane OSB confirmed iconographer; last public evidence 2019 — verify current activity before outreach",
    "lat": 45.07,
    "lon": -122.79
  },
  {
    "id": "pluscarden-abbey",
    "name": "Pluscarden Abbey",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Elgin",
    "region": "Moray",
    "country": "Scotland",
    "disciplines": [
      "Stone carving",
      "Wood carving",
      "Architectural ornament"
    ],
    "website": "https://www.pluscardenabbey.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Contemporary artworks by four brethren",
      "new St Joseph's Retreat stonework 2024"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Diocese of Aberdeen",
    "activeSince": 2024,
    "sourceUrl": "https://www.pluscardenabbey.org/contemporary-art-work",
    "notes": "Four monks listed as producing original art 2023; external carver Philip Chatfield also working on site 2024",
    "lat": 57.65,
    "lon": -3.32
  },
  {
    "id": "abbaye-sainte-madeleine-du-barroux",
    "name": "Abbaye Sainte-Madeleine du Barroux",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Le Barroux",
    "region": "Provence",
    "country": "France",
    "disciplines": [
      "Liturgical textiles",
      "Illumination",
      "Calligraphy"
    ],
    "website": "https://www.barroux.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Abbey church",
      "monastic publications",
      "gift shop"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Diocese of Avignon",
    "activeSince": 2022,
    "sourceUrl": "https://www.liturgicalartsjournal.com/2022/08/abbaye-sainte-madeleine-du-barroux-le.html",
    "notes": "~60 monks; shop confirmed active; no individual named artist-monk publicly confirmed",
    "lat": 44.13,
    "lon": 5.1
  },
  {
    "id": "conception-abbey",
    "name": "Conception Abbey",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Conception",
    "region": "Missouri",
    "country": "USA",
    "disciplines": [
      "Calligraphy",
      "Illumination"
    ],
    "website": "https://www.conceptionabbey.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "'Lettering the Word' calligraphy retreats (2026 dates confirmed",
      "2026 July fully booked)"
    ],
    "training": "Benedictine monastic formation; Foundational Hand 10th-century tradition",
    "endorser": "Diocese of Kansas City-St. Joseph",
    "activeSince": 2024,
    "sourceUrl": "https://www.conceptionabbey.org/guests/calligraphy-retreats/",
    "notes": "Calligraphy retreat program active and booked 2026; no single named artist-monk publicly confirmed",
    "lat": 40.24,
    "lon": -94.69
  },
  {
    "id": "benedictine-sisters-of-perpetual-adoration",
    "name": "Benedictine Sisters of Perpetual Adoration",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Clyde",
    "region": "Missouri",
    "country": "USA",
    "disciplines": [
      "Vestments",
      "Liturgical textiles"
    ],
    "website": "https://www.benedictinesisters.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Liturgical vestments for dioceses",
      "altar breads"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Diocese of Kansas City-St. Joseph",
    "activeSince": 2024,
    "sourceUrl": "https://www.dakotanewsnow.com/",
    "notes": "Vestment program confirmed active 2024; workshop-level entry",
    "lat": 40.27,
    "lon": -94.74
  },
  {
    "id": "benedictine-monastery-of-norcia-patron",
    "name": "Benedictine Monastery of Norcia (patron)",
    "type": "Monastery workshop",
    "order": "OSB",
    "city": "Norcia",
    "region": "Umbria",
    "country": "Italy",
    "disciplines": [
      "Fresco",
      "Panel painting",
      "Architectural ornament"
    ],
    "website": "https://www.nursia.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "New sanctuary paintings 2024–2025 by commissioned artist Fabrizio Diomedi (lay)"
    ],
    "training": "Benedictine monastic formation",
    "endorser": "Diocese of Spoleto-Norcia",
    "activeSince": 2024,
    "sourceUrl": "https://www.newliturgicalmovement.org/2024/05/norcias-new-sanctuary-paintings-in.html",
    "notes": "Primary producing artist is lay (see Fabrizio Diomedi entry); monastery is patron not producer",
    "lat": 42.79,
    "lon": 13.1
  },
  {
    "id": "talleres-de-arte-granda",
    "name": "Talleres de Arte Granda",
    "type": "Lay atelier",
    "order": null,
    "city": "Alcalá de Henares",
    "region": "Madrid",
    "country": "Spain",
    "disciplines": [
      "Sculpture",
      "Liturgical metalwork",
      "Vestments",
      "Liturgical textiles",
      "Fresco",
      "Mosaic",
      "Stained glass"
    ],
    "website": "https://granda.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Commissions across 5 continents",
      "Our Lady of Belen Chapel Miami 2022",
      "Vatican commissions"
    ],
    "training": "Founded 1891 Fr. Félix Granda; multigenerational ateliers",
    "endorser": "Vatican; dioceses worldwide",
    "activeSince": 2022,
    "sourceUrl": "https://granda.com/en/granda/",
    "notes": "Large multi-disciplinary workshop; Artistic Director Lucas Viar (architect)",
    "lat": 40.48,
    "lon": -3.36
  },
  {
    "id": "l-atelier-romanitas",
    "name": "L'Atelier Romanitas",
    "type": "Lay atelier",
    "order": null,
    "city": "Lyon",
    "region": "Auvergne-Rhône-Alpes",
    "country": "France",
    "disciplines": [
      "Vestments",
      "Liturgical textiles"
    ],
    "website": "https://www.romanitas.fr",
    "email": null,
    "social": null,
    "notableWorks": [
      "Roman and baroque vestments for FSSP and diocesan clergy worldwide"
    ],
    "training": "Baroque vestment tradition; Lyon liturgical heritage",
    "endorser": "FSSP; various dioceses",
    "activeSince": 2022,
    "sourceUrl": "https://www.liturgicalartsjournal.com/2022/03/further-considerations-of-vestments.html",
    "notes": "Active bespoke atelier confirmed 2022; no named individual publicly confirmed",
    "lat": 45.76,
    "lon": 4.84
  },
  {
    "id": "sacra-domus-aurea",
    "name": "Sacra Domus Aurea",
    "type": "Lay atelier",
    "order": null,
    "city": null,
    "region": null,
    "country": "Italy",
    "disciplines": [
      "Vestments",
      "Liturgical textiles"
    ],
    "website": "https://www.sacradomusaurea.com",
    "email": null,
    "social": "@sacradomusaurea",
    "notableWorks": [
      "Guadalupe vestment series 2024",
      "multiple sets featured Liturgical Arts Journal 2024–2026"
    ],
    "training": "Traditional embroidery; Italian craft",
    "endorser": "Multiple dioceses/parishes",
    "activeSince": 2024,
    "sourceUrl": "https://www.liturgicalartsjournal.com/2024/12/variations-on-theme-guadalupe-vestments.html",
    "notes": "Made in Italy; bespoke on-demand; ships internationally; Facebook 12700+ followers",
    "lat": 41.87,
    "lon": 12.57
  },
  {
    "id": "scuola-beato-angelico",
    "name": "Scuola Beato Angelico",
    "type": "Lay atelier",
    "order": null,
    "city": "Milan",
    "region": "Lombardy",
    "country": "Italy",
    "disciplines": [
      "Mosaic",
      "Fresco",
      "Panel painting",
      "Stained glass",
      "Vestments",
      "Liturgical metalwork",
      "Sculpture"
    ],
    "website": "https://www.devotio.it/en/exhibitors-2021/fondazionesba.html",
    "email": null,
    "social": null,
    "notableWorks": [
      "Altars paintings frescoes mosaics liturgical objects Italy and abroad"
    ],
    "training": "Founded 1924 by Archbishop Schuster; multigenerational sacred art formation",
    "endorser": "Archdiocese of Milan; Vatican",
    "activeSince": 2021,
    "sourceUrl": "https://www.devotio.it/en/exhibitors-2021/fondazionesba.html",
    "notes": "Fondazione di Culto active school/atelier; no individual artist names confirmed in this pass",
    "lat": 45.46,
    "lon": 9.19
  },
  {
    "id": "studio-of-john-the-baptist",
    "name": "Studio of John the Baptist",
    "type": "Lay atelier",
    "order": null,
    "city": "Auckland",
    "region": null,
    "country": "New Zealand",
    "disciplines": [
      "Iconography",
      "Panel painting",
      "Mosaic"
    ],
    "website": "https://www.sacredart.co.nz",
    "email": null,
    "social": null,
    "notableWorks": [
      "Commissions for cathedrals and churches in NZ and Australia"
    ],
    "training": "Founded 2005; training details not confirmed",
    "endorser": "Catholic Diocese of Auckland",
    "activeSince": 2022,
    "sourceUrl": "https://www.sacredart.co.nz",
    "notes": "Website active; no named individual artist publicly listed; studio-level entry",
    "lat": -36.85,
    "lon": 174.76
  },
  {
    "id": "fabrizio-diomedi",
    "name": "Fabrizio Diomedi",
    "type": "Individual",
    "order": null,
    "city": "Corridonia",
    "region": "Marche",
    "country": "Italy",
    "disciplines": [
      "Panel painting",
      "Fresco",
      "Architectural ornament",
      "Liturgical textiles"
    ],
    "website": null,
    "email": null,
    "social": "@fabriziodiomedi",
    "notableWorks": [
      "Norcia Monastery sanctuary paintings 2024",
      "Norcia Nativity 2025",
      "1st Prize Catholic Art Institute Sacred Art Prize 2024 (San Vincenzo Maria Strambi)"
    ],
    "training": "Self-trained; NeoUmbrian style; developed with Monks of Norcia",
    "endorser": "Monastery of Norcia; Catholic Art Institute",
    "activeSince": 2024,
    "sourceUrl": "https://www.liturgicalartsjournal.com/2025/05/the-tradition-of-decorative-textiles-in.html",
    "notes": "Active 2014–2026; social media confirmed; based Corridonia Marche",
    "lat": 43.25,
    "lon": 13.5
  },
  {
    "id": "martin-earle",
    "name": "Martin Earle",
    "type": "Individual",
    "order": null,
    "city": "Shrewsbury",
    "region": "England",
    "country": "United Kingdom",
    "disciplines": [
      "Panel painting",
      "Iconography",
      "Mosaic",
      "Stone carving",
      "Sculpture"
    ],
    "website": "https://www.martinearle.com",
    "email": null,
    "social": "@martinearle_art",
    "notableWorks": [
      "9ft crucifix Aberdeen Cathedral 2023",
      "2nd Prize CAI 2024",
      "Grand Prize CAI 2023",
      "carved crucifix Beda College Rome 2022"
    ],
    "training": "Trained under Aidan Hart; co-founder Chichester Workshop for Liturgical Art",
    "endorser": "Aberdeen Cathedral; Pontifical Beda College Rome",
    "activeSince": 2022,
    "sourceUrl": "https://martinearle.com/about/",
    "notes": "Based UK working internationally; active 2021–2026 confirmed",
    "lat": 52.71,
    "lon": -2.75
  },
  {
    "id": "james-blackstone",
    "name": "James Blackstone",
    "type": "Individual",
    "order": null,
    "city": "Shrewsbury",
    "region": "England",
    "country": "United Kingdom",
    "disciplines": [
      "Iconography",
      "Mosaic"
    ],
    "website": "https://www.chichesterworkshop.org",
    "email": null,
    "social": "@dunstanicons",
    "notableWorks": [
      "Mosaic of St. Dominic Chichester Cathedral 2022",
      "Grand Prize CAI 2023 co-winner San Damiano Crucifix"
    ],
    "training": "Trained under Aidan Hart and Martin Earle; co-founder Chichester Workshop",
    "endorser": "Chichester Cathedral; Ealing Abbey",
    "activeSince": 2022,
    "sourceUrl": "https://www.chichestercathedral.org.uk/james-blackstone",
    "notes": "Chichester Cathedral page describes as Anglican; takes Catholic commissions — note affiliation in outreach",
    "lat": 52.71,
    "lon": -2.75
  },
  {
    "id": "aidan-hart",
    "name": "Aidan Hart",
    "type": "Individual",
    "order": null,
    "city": "Shrewsbury",
    "region": "England",
    "country": "United Kingdom",
    "disciplines": [
      "Iconography",
      "Fresco",
      "Mosaic",
      "Wood carving",
      "Stone carving",
      "Sculpture"
    ],
    "website": "https://www.aidanharticons.com",
    "email": "mail@aidanharticons.com",
    "social": null,
    "notableWorks": [
      "1200+ commissions in 25+ countries",
      "Orthodox and Catholic churches",
      "published Techniques of Icon and Wall Painting"
    ],
    "training": "Self-trained 1978–; Byzantine tradition; founded Icon Certificate Programme Prince's Foundation",
    "endorser": "Commissions in UK US France Russia",
    "activeSince": 2024,
    "sourceUrl": "https://www.aidanharticons.com",
    "notes": "Greek Orthodox; explicitly takes Catholic commissions worldwide; most authoritative living iconographer in English-speaking world; active 2024",
    "lat": 52.71,
    "lon": -2.75
  },
  {
    "id": "chichester-workshop-for-liturgical-art",
    "name": "Chichester Workshop for Liturgical Art",
    "type": "Lay atelier",
    "order": null,
    "city": "Chichester",
    "region": "West Sussex",
    "country": "United Kingdom",
    "disciplines": [
      "Iconography",
      "Mosaic",
      "Panel painting",
      "Fresco"
    ],
    "website": "https://www.chichesterworkshop.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "San Damiano Crucifix Aberdeen 2023",
      "mosaic St. Dominic Chichester 2022",
      "active apprenticeship programme"
    ],
    "training": "Master-apprentice formation: Earle/Blackstone/Hart",
    "endorser": "Chichester Cathedral; Pontifex University",
    "activeSince": 2022,
    "sourceUrl": "https://www.newliturgicalmovement.org/2023/10/an-artistic-feeding-of-five-thousand.html",
    "notes": "Founded by Martin Earle Aidan Hart James Blackstone; teaching atelier with active commissions",
    "lat": 50.84,
    "lon": -0.78
  },
  {
    "id": "juan-alberto-perez-rojas",
    "name": "Juan Alberto Pérez Rojas",
    "type": "Individual",
    "order": null,
    "city": "Seville",
    "region": "Andalusia",
    "country": "Spain",
    "disciplines": [
      "Sculpture"
    ],
    "website": "https://www.escultorperezrojas.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Virgen del Carmen for Parroquia San Juan Pablo II Montequinto 2022",
      "international commissions"
    ],
    "training": "Faculty of Fine Arts; specialised in imaginería polícroma",
    "endorser": "Gremio Sevillana de Arte Sacro; Archdiocese of Seville",
    "activeSince": 2022,
    "sourceUrl": "https://gremioartesacro.com/asociados/alberto-perez-rojas/",
    "notes": "Born 1982 Ronda; workshop in San Lorenzo barrio Seville since 2009; active imaginero tradition",
    "lat": 37.39,
    "lon": -5.99
  },
  {
    "id": "marek-czarnecki",
    "name": "Marek Czarnecki",
    "type": "Individual",
    "order": null,
    "city": "Meriden",
    "region": "Connecticut",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.seraphicrestorations.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Icons Cathedral of Immaculate Conception Springfield IL",
      "Franciscan University Steubenville",
      "Connecticut churches"
    ],
    "training": "School of Visual Arts BFA 1987; Ksenia Pokrovsky / Vladislav Andrejev Prosopon/Izograph",
    "endorser": "Franciscan University of Steubenville; multiple CT parishes",
    "activeSince": 2021,
    "sourceUrl": "https://endersisland.secure.retreat.guru/teacher/marek-czarnecki/",
    "notes": "Roman Catholic; teaches and writes from Meriden CT studio; active 2021–2024 confirmed",
    "lat": 41.54,
    "lon": -72.81
  },
  {
    "id": "daniel-mitsui",
    "name": "Daniel Mitsui",
    "type": "Individual",
    "order": null,
    "city": "Hobart",
    "region": "Indiana",
    "country": "USA",
    "disciplines": [
      "Pen and ink",
      "Illumination",
      "Calligraphy"
    ],
    "website": "https://www.danielmitsui.com",
    "email": null,
    "social": "@danielmitsui_artist",
    "notableWorks": [
      "Illuminated manuscript-style commissions on calfskin",
      "medieval Gothic and Japanese-influenced ink works",
      "blog active May 2026"
    ],
    "training": "Self-trained in medieval manuscript tradition; Gothic Celtic Persian Japanese influences",
    "endorser": "Catholic Art Guild Chicago; Catholic Art Institute",
    "activeSince": 2021,
    "sourceUrl": "https://catholicartistconnection.com/blog/meet-indiana-based-artist-daniel-mitsui",
    "notes": "Active May 2026 (YouTube interview confirmed); sells originals and prints; specialises in calfskin vellum",
    "lat": 41.53,
    "lon": -87.27
  },
  {
    "id": "jed-gibbons",
    "name": "Jed Gibbons",
    "type": "Individual",
    "order": null,
    "city": "Chicago",
    "region": "Illinois",
    "country": "USA",
    "disciplines": [
      "Illumination",
      "Panel painting"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Illuminated paintings St. Mary of the Assumption Lancaster OH renovation",
      "Catholic Art Guild Chicago instructor"
    ],
    "training": "Medieval illumination tradition; detailed figurative panel painting",
    "endorser": "St. John Cantius Chicago; multiple parishes",
    "activeSince": 2021,
    "sourceUrl": "https://www.liturgicalartsjournal.com/2019/12/before-and-after-st-mary-of-assumption.html",
    "notes": "No current standalone website confirmed; active 2021 per Catholic Art Institute; Chicago-based",
    "lat": 41.88,
    "lon": -87.63
  },
  {
    "id": "matthew-alderman",
    "name": "Matthew Alderman",
    "type": "Individual",
    "order": null,
    "city": "Minneapolis",
    "region": "Minnesota",
    "country": "USA",
    "disciplines": [
      "Architectural ornament",
      "Liturgical metalwork",
      "Pen and ink",
      "Vestments"
    ],
    "website": "https://matthewalderman.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Baldachin/altar/floor Our Lady of the Rosary Parish",
      "book cover illustration 2024 Chrism Press"
    ],
    "training": "Notre Dame architecture Rambusch Prize 2006; classical design training",
    "endorser": "Notre Dame; multiple parishes",
    "activeSince": 2024,
    "sourceUrl": "https://matthewalderman.com/press-1",
    "notes": "Architect/designer/illustrator; active 2024",
    "lat": 44.98,
    "lon": -93.27
  },
  {
    "id": "neilson-carlin",
    "name": "Neilson Carlin",
    "type": "Individual",
    "order": null,
    "city": "Kennett Square",
    "region": "Pennsylvania",
    "country": "USA",
    "disciplines": [
      "Panel painting"
    ],
    "website": "https://www.neilsoncarlin.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Holy Family image World Meeting of Families 2015",
      "large-scale parish sacred paintings nationwide"
    ],
    "training": "BFA University of the Arts Philadelphia; trained under Michael Aviano",
    "endorser": "Archdiocese of Philadelphia; multiple dioceses",
    "activeSince": 2021,
    "sourceUrl": "https://www.carlinacademy.com/neilson-carlin",
    "notes": "Also runs Carlin Academy of Fine Art; specialises in monumental sacred paintings",
    "lat": 39.85,
    "lon": -75.71
  },
  {
    "id": "anthony-visco",
    "name": "Anthony Visco",
    "type": "Individual",
    "order": null,
    "city": "Philadelphia",
    "region": "Pennsylvania",
    "country": "USA",
    "disciplines": [
      "Sculpture",
      "Fresco"
    ],
    "website": "https://www.anthonyviscoartist.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "National Shrine Saint Rita of Cascia Philadelphia",
      "Via Crucis Shrine Our Lady of Guadalupe La Crosse WI",
      "triptych reliefs Bryn Mawr"
    ],
    "training": "BFA Philadelphia College of Art; Fulbright-Hayes Grant; Accademia Belle Arti Florence",
    "endorser": "Shrine Our Lady of Guadalupe La Crosse; Archdiocese of Philadelphia",
    "activeSince": 2024,
    "sourceUrl": "https://endersisland.secure.retreat.guru/teacher/anthony-visco/",
    "notes": "Founder/Director Atelier for the Sacred Arts and St. Edmund's Sacred Art Institute Enders Island CT",
    "lat": 39.95,
    "lon": -75.17
  },
  {
    "id": "andrew-wilson-smith",
    "name": "Andrew Wilson Smith",
    "type": "Individual",
    "order": null,
    "city": "Tennessee",
    "region": "Tennessee",
    "country": "USA",
    "disciplines": [
      "Stone carving",
      "Sculpture",
      "Mosaic"
    ],
    "website": "https://www.awssculpturestudio.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Annunciation Capitals and lintel Clear Creek Abbey Oklahoma (National Eucharistic Congress 2024)",
      "statuary stone/bronze/plaster"
    ],
    "training": "15+ years classical sculpture training",
    "endorser": "Clear Creek Abbey OSB; National Eucharistic Congress",
    "activeSince": 2024,
    "sourceUrl": "https://catholicartistsdirectory.com/tympanum",
    "notes": "Active 2024 per NEC exhibit; multiple materials; based TN",
    "lat": 35.86,
    "lon": -86.66
  },
  {
    "id": "george-carpenter",
    "name": "George Carpenter",
    "type": "Individual",
    "order": null,
    "city": "Hulbert",
    "region": "Oklahoma",
    "country": "USA",
    "disciplines": [
      "Stone carving",
      "Architectural ornament"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Tympanum Christ enthroned Clear Creek Abbey Church 2020",
      "metalwork for abbey"
    ],
    "training": "Self-trained stone carver; French Romanesque tradition",
    "endorser": "Clear Creek Abbey OSB",
    "activeSince": 2021,
    "sourceUrl": "https://media.benedictine.edu/making-stone-speak-clear-creeks-gate-of-heaven",
    "notes": "Lives near Clear Creek Abbey; seven-year project completed 2020; no public website found",
    "lat": 35.93,
    "lon": -95.13
  },
  {
    "id": "henry-wingate",
    "name": "Henry Wingate",
    "type": "Individual",
    "order": null,
    "city": "Madison",
    "region": "Virginia",
    "country": "USA",
    "disciplines": [
      "Panel painting",
      "Watercolor"
    ],
    "website": "https://www.henrywingate.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Sacred Heart commission Virginia 2024",
      "portraits and landscapes",
      "religious commissions"
    ],
    "training": "Boston School tradition; classical figurative oil painting",
    "endorser": "Catholic parishes; Way of Beauty blog",
    "activeSince": 2024,
    "sourceUrl": "https://wayofbeauty.squarespace.com/blog/tag/Henry+Wingate",
    "notes": "Virginia-based; confirmed active 2024",
    "lat": 38.38,
    "lon": -78.26
  },
  {
    "id": "gwyneth-thompson-briggs",
    "name": "Gwyneth Thompson-Briggs",
    "type": "Individual",
    "order": null,
    "city": "St. Louis",
    "region": "Missouri",
    "country": "USA",
    "disciplines": [
      "Panel painting"
    ],
    "website": "https://www.gwynthompsonbriggssacredart.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Full-time sacred art commissions",
      "saints portrait series",
      "featured Our Sunday Visitor 2024"
    ],
    "training": "Oil painting classical Western tradition; self-developed",
    "endorser": "Archdiocese of St. Louis; OSV",
    "activeSince": 2023,
    "sourceUrl": "https://www.oursundayvisitor.com/a-very-human-life-is-the-hallmark-of-gwyneth-thompson-briggs-sacred-art/",
    "notes": "Full-time sacred artist since ~2019; paints commissions and teaches; active 2023–2024",
    "lat": 38.63,
    "lon": -90.2
  },
  {
    "id": "cody-swanson",
    "name": "Cody Swanson",
    "type": "Individual",
    "order": null,
    "city": "Florence",
    "region": "Tuscany",
    "country": "Italy",
    "disciplines": [
      "Sculpture"
    ],
    "website": "https://www.catholicartinstitute.org/codyswanson",
    "email": null,
    "social": null,
    "notableWorks": [
      "Madonna and Child marble Monastery Norcia 2020",
      "Mary Mother of Fairest Love shrine sculpture 2022"
    ],
    "training": "Sacred Art School Florence; classical marble and bronze",
    "endorser": "Monastery of Norcia; multiple US/European churches",
    "activeSince": 2022,
    "sourceUrl": "https://www.catholicartinstitute.org/codyswanson",
    "notes": "American sculptor based Florence Italy; active 2020–2022+ confirmed",
    "lat": 43.77,
    "lon": 11.26
  },
  {
    "id": "tianna-williams",
    "name": "Tianna Williams",
    "type": "Individual",
    "order": null,
    "city": "Bruno",
    "region": "Saskatchewan",
    "country": "Canada",
    "disciplines": [
      "Panel painting"
    ],
    "website": "https://www.sacredartbytianna.com",
    "email": null,
    "social": "@sacredartbytianna",
    "notableWorks": [
      "Collaboration Ascension Press St. Charles Lwanga 2022",
      "commission St. Joseph's Basilica Edmonton 2022",
      "saints portrait series"
    ],
    "training": "Oil painting; self-taught; graphic design background",
    "endorser": "Archdiocese of Edmonton; Ascension Press; Word on Fire",
    "activeSince": 2022,
    "sourceUrl": "https://catholicartistconnection.com/blog/meet-bruno-based-artist-tianna-williams",
    "notes": "Saskatchewan Canada; full-time Catholic artist; active 2022–2026 confirmed",
    "lat": 52.27,
    "lon": -105.5
  },
  {
    "id": "timothy-schmalz",
    "name": "Timothy Schmalz",
    "type": "Individual",
    "order": null,
    "city": "St. Jacobs",
    "region": "Ontario",
    "country": "Canada",
    "disciplines": [
      "Sculpture"
    ],
    "website": "https://www.timothypaulschmalz.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Homeless Jesus (50+ casts worldwide including Vatican)",
      "Angels Unawares St. Peter's Square 2019",
      "Carlos Acutis sculpture NEC Indianapolis 2024",
      "Cathedral Gardens Quebec City 2024"
    ],
    "training": "Self-trained sculptor; bronze primary medium",
    "endorser": "Vatican (Pope Francis); St. Peter's Square; Shrine Padre Pio",
    "activeSince": 2024,
    "sourceUrl": "https://en.wikipedia.org/wiki/Timothy_Schmalz",
    "notes": "Most widely installed living Catholic sculptor; papal commissions; active 2024–2026 confirmed",
    "lat": 43.54,
    "lon": -80.55
  },
  {
    "id": "andre-prevost",
    "name": "Andre Prevost",
    "type": "Individual",
    "order": null,
    "city": "Alberta",
    "region": "Alberta",
    "country": "Canada",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "First Nations icons series (Siksika Sacred Heart",
      "Immaculate Heart of Mary)",
      "icons for Ukrainian Catholic and Latin Rite churches Canada"
    ],
    "training": "Self-taught; Byzantine tradition; 35+ years practice",
    "endorser": "Sacred Heart Parish Vancouver OMI; Ukrainian Catholic Eparchy Edmonton",
    "activeSince": 2024,
    "sourceUrl": "https://bccatholic.ca/news/catholic-van/artist-navigates-uncharted-waters-of-indigenous-iconography",
    "notes": "French Canadian Catholic iconographer; no standalone website confirmed; active 2024",
    "lat": 53.93,
    "lon": -116.58
  },
  {
    "id": "steve-knight",
    "name": "Steve Knight",
    "type": "Individual",
    "order": null,
    "city": "Burnaby",
    "region": "British Columbia",
    "country": "Canada",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.epiphanysacredartsguild.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "80+ icons for Vancouver churches",
      "Stations of the Cross Sts. Joachim and Ann Aldergrove in progress 2024–2025",
      "banners for Vancouver 2014 canonization"
    ],
    "training": "BA Classics UBC; formal painting training UBC",
    "endorser": "Archdiocese of Vancouver; multiple parishes",
    "activeSince": 2024,
    "sourceUrl": "https://bccatholic.ca/news/catholic-van/one-standout-icon-forced-artist-to-revise-his-fifth-station-of-the-cross",
    "notes": "President Epiphany Sacred Arts Guild Vancouver; active December 2024–May 2025 confirmed",
    "lat": 49.25,
    "lon": -122.96
  },
  {
    "id": "dave-and-maria-guadalupe-levangie",
    "name": "Dave and Maria Guadalupe Levangie",
    "type": "Lay atelier",
    "order": null,
    "city": "Halifax",
    "region": "Nova Scotia",
    "country": "Canada",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": "kalos@iconografia.mx",
    "notableWorks": [
      "Kalos Iconography retreats Mexico (4 editions 2022–2024) and Canada Halifax 2024"
    ],
    "training": "Maria trained Mexico; egg tempera traditional iconography",
    "endorser": "Archdiocese of Halifax-Yarmouth; St. Francis and St. Clare Parish",
    "activeSince": 2024,
    "sourceUrl": "https://www.catholicregister.org/item/746-iconography-from-darkness-to-light",
    "notes": "Active 2024; email publicly listed per Catholic Register article; joint couple-led atelier; based Halifax/Mexico",
    "lat": 44.65,
    "lon": -63.58
  },
  {
    "id": "michael-galovic",
    "name": "Michael Galovic",
    "type": "Individual",
    "order": null,
    "city": "New South Wales",
    "region": "New South Wales",
    "country": "Australia",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.michaelgalovic.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "100+ church commissions Australia",
      "trilogy St. Joseph's Rosebery Sydney 2021",
      "St. Ignatius Loyola for St. Ignatius College Riverview (Jesuits)",
      "Blake Prize finalist 4x"
    ],
    "training": "Belgrade Academy of Arts 1974; 50+ years iconographer",
    "endorser": "Archdiocese of Sydney; Jesuits Australia",
    "activeSince": 2024,
    "sourceUrl": "https://catholicweekly.com.au/tag/michael-galovic/",
    "notes": "Serbian-born Australian; one of Australia's leading iconographers; active 2024 confirmed",
    "lat": -32,
    "lon": 147
  },
  {
    "id": "fr-jon-buffington",
    "name": "Fr. Jon Buffington",
    "type": "Individual",
    "order": null,
    "city": "Portland",
    "region": "Oregon",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.agiosiconstudio.com",
    "email": "frjon@msn.com",
    "social": null,
    "notableWorks": [
      "Icons in churches Oregon and multiple states/countries",
      "Trinity Iconography Institute Portland"
    ],
    "training": "MA Patristics GTU Berkeley; trained Mount Angel Seminary; Master Iconographer Trinity Cathedral Portland",
    "endorser": "Archdiocese of Portland; multiple parishes",
    "activeSince": 2022,
    "sourceUrl": "https://agiosiconstudio.com",
    "notes": "Chaldean Catholic priest in Archdiocese of Portland; email publicly listed on website; active 2022",
    "lat": 45.52,
    "lon": -122.68
  },
  {
    "id": "david-clayton",
    "name": "David Clayton",
    "type": "Individual",
    "order": null,
    "city": "Princeton",
    "region": "New Jersey",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.thewayofbeauty.org",
    "email": null,
    "social": "@david_way_beauty",
    "notableWorks": [
      "Church commissions US and UK",
      "books The Way of Beauty",
      "Dean Faculty of Sacred Arts Pontifex University",
      "Scala Foundation Artist-in-Residence"
    ],
    "training": "Byzantine iconography trained under Aidan Hart; portrait painting Florence Italy",
    "endorser": "Scala Foundation; Pontifex University; Thomas More College",
    "activeSince": 2024,
    "sourceUrl": "https://scalafoundation.org/about-david-clayton/",
    "notes": "Oxford-educated; active 2024",
    "lat": 40.35,
    "lon": -74.66
  },
  {
    "id": "fr-silouan-justiniano",
    "name": "Fr. Silouan Justiniano",
    "type": "Individual",
    "order": null,
    "city": "New York",
    "region": "New York",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://hieromonksilouan.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Woman Clothed with the Sun icon 2nd Prize CAI 2023",
      "1st Prize CAI Sacred Art Prize 2020",
      "icons for Puerto Rico and North America"
    ],
    "training": "Byzantine iconography tradition; monastery formation; Orthodox Arts Journal contributor",
    "endorser": "Catholic Art Institute; multiple churches",
    "activeSince": 2021,
    "sourceUrl": "https://orthodoxartsjournal.org/fr-silouan-justiniano/",
    "notes": "Orthodox hieromonk; entered and won Catholic Art Institute competition; note Orthodox affiliation but takes Catholic commissions",
    "lat": 40.71,
    "lon": -74.01
  },
  {
    "id": "jacek-hajnos-op",
    "name": "Jacek Hajnos OP",
    "type": "Individual",
    "order": "OP",
    "city": "Warsaw",
    "region": "Masovian",
    "country": "Poland",
    "disciplines": [
      "Panel painting",
      "Pen and ink",
      "Sculpture"
    ],
    "website": null,
    "email": null,
    "social": "@jackhajnos",
    "notableWorks": [
      "Annunciation paintings Let's Paint Catholicism Again Rome 2024",
      "Visitation paintings Warsaw 2024–2025",
      "national spiritual director Art Vera Icon community"
    ],
    "training": "ASP Kraków Academy of Fine Arts; Dominican formation",
    "endorser": "Dominican Province Poland; Angelicum Rome",
    "activeSince": 2024,
    "sourceUrl": "https://info.dominikanie.pl/2024/12/nawiedzenie-namalowane-od-nowa/",
    "notes": "Active friar-painter; December 2024 exhibition confirmed",
    "lat": 52.23,
    "lon": 21.01
  },
  {
    "id": "ignacy-czwartos",
    "name": "Ignacy Czwartos",
    "type": "Individual",
    "order": null,
    "city": "Warsaw",
    "region": "Masovian",
    "country": "Poland",
    "disciplines": [
      "Panel painting"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "History paintings",
      "Let's Paint Catholicism Again Annunciation 2024",
      "solo exhibition Zachęta Warsaw 2023",
      "Polonia Uncensored Venice Biennale 2024"
    ],
    "training": "Academy of Fine Arts; figurative historical tradition",
    "endorser": "Angelicum Rome (JPII Institute); national cultural institutions",
    "activeSince": 2024,
    "sourceUrl": "https://northtexascatholic.org/news/sacred-art-project-aims-to-revive-the-language-of-the-image-in-communicating-the-faith",
    "notes": "Born 1966; Catholic figurative painter; active 2023–2024 confirmed; primarily history/figure painter, not exclusively liturgical",
    "lat": 52.23,
    "lon": 21.01
  },
  {
    "id": "bogna-podbielska",
    "name": "Bogna Podbielska",
    "type": "Individual",
    "order": null,
    "city": "Warsaw",
    "region": "Masovian",
    "country": "Poland",
    "disciplines": [
      "Panel painting"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Divine Mercy and Annunciation paintings Let's Paint Catholicism Again 2023–2024"
    ],
    "training": "Fine arts training (unverified)",
    "endorser": "Angelicum Rome; Saint Nicholas Foundation",
    "activeSince": 2023,
    "sourceUrl": "https://angelicum.it/st-john-paul-ii-institute-of-culture/lets-paint-catholicism-again/",
    "notes": "Part of core Let's Paint Catholicism Again group; active 2023–2024; no standalone website confirmed",
    "lat": 52.23,
    "lon": 21.01
  },
  {
    "id": "beata-stankiewicz",
    "name": "Beata Stankiewicz",
    "type": "Individual",
    "order": null,
    "city": "Warsaw",
    "region": "Masovian",
    "country": "Poland",
    "disciplines": [
      "Panel painting"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Divine Mercy and Annunciation paintings Let's Paint Catholicism Again 2023–2024"
    ],
    "training": "Fine arts training (unverified)",
    "endorser": "Angelicum Rome; Saint Nicholas Foundation",
    "activeSince": 2023,
    "sourceUrl": "https://dlcenter.org/2022/to-paint-catholicism-anew-we-took-part-in-a-conference-on-sacred-art/",
    "notes": "Part of core group; active 2023–2024; no standalone website confirmed",
    "lat": 52.23,
    "lon": 21.01
  },
  {
    "id": "olya-kravchenko",
    "name": "Olya Kravchenko",
    "type": "Individual",
    "order": null,
    "city": "Lviv",
    "region": "Lviv Oblast",
    "country": "Ukraine",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://iconart-gallery.com/artists/olga-kravchenko/",
    "email": null,
    "social": null,
    "notableWorks": [
      "Museum of Archdiocese Warsaw exhibition 2022",
      "Christmas in the Air Raid Shelter 2024",
      "audiovisual icon project 2023"
    ],
    "training": "Lviv National Academy of Arts restoration dept 2002–2008; Ministry of Culture Poland grant Gaude Polonia 2008",
    "endorser": "Archdiocese Warsaw; National Union of Artists of Ukraine",
    "activeSince": 2024,
    "sourceUrl": "https://artandtheology.org/tag/olya-kravchenko/",
    "notes": "Ukrainian Greek Catholic (implied by Lviv/church commissions); note rite Eastern; active 2023–2024 confirmed",
    "lat": 49.84,
    "lon": 24.03
  },
  {
    "id": "martine-boutros",
    "name": "Martine Boutros",
    "type": "Individual",
    "order": null,
    "city": "Beirut",
    "region": null,
    "country": "Lebanon",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.martineicons.com",
    "email": null,
    "social": null,
    "notableWorks": [
      "Icons for Maronite parishes",
      "commissions accepted internationally"
    ],
    "training": "Iconography training at Iconographiste atelier Kfarmashoun under Sister Therese al Chayeb 2018–2020",
    "endorser": "Maronite Church Lebanon",
    "activeSince": 2024,
    "sourceUrl": "https://www.martineicons.com",
    "notes": "Note rite: Maronite; website active 2024; accepting commissions",
    "lat": 33.89,
    "lon": 35.5
  },
  {
    "id": "joseph-el-masri",
    "name": "Joseph El-Masri",
    "type": "Individual",
    "order": null,
    "city": "Beirut",
    "region": null,
    "country": "Lebanon",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": "@iconography.joseph",
    "notableWorks": [
      "Mystical Supper icon for Maronite Cathedral",
      "commissions for Maronite parishes",
      "TikTok active 2025"
    ],
    "training": "Byzantine iconographic tradition",
    "endorser": "Maronite Church Lebanon",
    "activeSince": 2024,
    "sourceUrl": "https://www.instagram.com/iconography.joseph/",
    "notes": "Note rite: Maronite; Instagram active 2025; phone +961 71 318564 (public per Facebook)",
    "lat": 33.89,
    "lon": 35.5
  },
  {
    "id": "bruce-onobrakpeya",
    "name": "Bruce Onobrakpeya",
    "type": "Individual",
    "order": null,
    "city": "Lagos",
    "region": "Lagos State",
    "country": "Nigeria",
    "disciplines": [
      "Panel painting",
      "Sculpture",
      "Mosaic"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Stations of the Cross St. Paul's Catholic Cathedral Lagos 1966–1978",
      "Smithsonian solo exhibition The Mask and the Cross 2024"
    ],
    "training": "Nigerian College of Arts Zaria; Zaria Radicals founding member",
    "endorser": "St. Paul's Catholic Cathedral Lagos; Smithsonian Institution",
    "activeSince": 2024,
    "sourceUrl": "https://africa.si.edu/2024/05/bruce-onobrakpeya-the-mask-and-the-cross-opens-june-21/",
    "notes": "Born 1932 age 92; active in Lagos studio 2024; historic Catholic commissions; primarily modernist tradition with Catholic content; not exclusively liturgical",
    "lat": 6.52,
    "lon": 3.38
  },
  {
    "id": "justino-cagayat-jr",
    "name": "Justino Cagayat Jr.",
    "type": "Individual",
    "order": null,
    "city": "Paete",
    "region": "Laguna",
    "country": "Philippines",
    "disciplines": [
      "Wood carving"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Official image of San Pedro Calungsod (canonized Filipino saint)",
      "continuous religious commission output",
      "GAMABA national living treasure awardee"
    ],
    "training": "Third-generation carver; family apprenticeship; batikuling wood",
    "endorser": "Philippine Catholic Church; parish and private commissions",
    "activeSince": 2023,
    "sourceUrl": "https://climatetracker.asia/carving-a-sustainable-future-how-paetes-woodcarvers-face-challenge-of-endangered-batikuling-tree/",
    "notes": "Catholic; Paete Laguna; active 2023 confirmed; no personal website found",
    "lat": 14.36,
    "lon": 121.48
  },
  {
    "id": "donald-jackson",
    "name": "Donald Jackson",
    "type": "Individual",
    "order": null,
    "city": "Wales",
    "region": null,
    "country": "United Kingdom",
    "disciplines": [
      "Calligraphy",
      "Illumination"
    ],
    "website": "https://www.saintjohnsbible.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "The Saint John's Bible (7 volumes",
      "commissioned by Saint John's Abbey Collegeville MN 1998–2011)",
      "Knight of Order of St. Gregory the Great (Vatican)"
    ],
    "training": "Central School of Arts and Crafts; Goldsmiths'; Bolton School of Art; 60+ years",
    "endorser": "Saint John's Abbey Collegeville MN OSB",
    "activeSince": 2021,
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3146388/",
    "notes": "Anglican; received papal knighthood for Catholic commission; born 1938, age 87 — confirm active status before outreach",
    "lat": 52.13,
    "lon": -3.78
  },
  {
    "id": "christine-thum-schlesser",
    "name": "Christine Thum Schlesser",
    "type": "Individual",
    "order": null,
    "city": "Oregon",
    "region": "Oregon",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": "https://www.classicaliconography.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "Director Classical Iconography Institute",
      "annual retreat Mount Angel Abbey 2024 (36 students)"
    ],
    "training": "Byzantine tradition; professional iconographer",
    "endorser": "Mount Angel Abbey OSB",
    "activeSince": 2024,
    "sourceUrl": "https://classicaliconography.org/retreat-2024/",
    "notes": "Catholic iconographer; directs annual institute at Mount Angel; active 2024",
    "lat": 44,
    "lon": -120.5
  },
  {
    "id": "philip-chatfield",
    "name": "Philip Chatfield",
    "type": "Individual",
    "order": null,
    "city": "Elgin",
    "region": "Moray",
    "country": "Scotland",
    "disciplines": [
      "Stone carving"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Multiple carved stones and statues Pluscarden Abbey St Joseph's Retreat 2024",
      "St. Brendan the Navigator carving Birnie Kirk"
    ],
    "training": "Trained under craftsman from Eric Gill arts and crafts workshop; active since 1978",
    "endorser": "Pluscarden Abbey OSB; Diocese of Aberdeen",
    "activeSince": 2024,
    "sourceUrl": "https://www.oldmonmothians.co.uk/post/carving-in-a-scottish-abbey",
    "notes": "External lay carver working for Pluscarden Abbey 2024; not a monk; confirmed active 2024",
    "lat": 57.65,
    "lon": -3.32
  },
  {
    "id": "daniel-delouise",
    "name": "Daniel DeLouise",
    "type": "Individual",
    "order": null,
    "city": "Mystic",
    "region": "Connecticut",
    "country": "USA",
    "disciplines": [
      "Panel painting"
    ],
    "website": "https://endersisland.org",
    "email": null,
    "social": null,
    "notableWorks": [
      "National Eucharistic Revival Art Competition organizer/juror 2024",
      "exhibited Enders Island and Blessed Michael McGivney Center New Haven"
    ],
    "training": "Sacred art formation Enders Island",
    "endorser": "St. Edmund's Sacred Art Institute; National Eucharistic Congress 2024",
    "activeSince": 2024,
    "sourceUrl": "https://www.oursundayvisitor.com/artists-are-invited-to-enter-this-special-sacred-art-competition/",
    "notes": "Artistic director St. Edmund's Sacred Art Institute; active 2024",
    "lat": 41.35,
    "lon": -71.97
  },
  {
    "id": "rochelle-hajjar",
    "name": "Rochelle Hajjar",
    "type": "Individual",
    "order": null,
    "city": "Beirut",
    "region": null,
    "country": "Lebanon",
    "disciplines": [
      "Sculpture",
      "Architectural ornament"
    ],
    "website": null,
    "email": null,
    "social": "@rochellehajjar_studio",
    "notableWorks": [
      "Sculptural commissions endorsed by Bishop Antoine-Charbel Tarabay Maronite",
      "serves Church through art"
    ],
    "training": "Training details not confirmed",
    "endorser": "Maronite Eparchy",
    "activeSince": 2025,
    "sourceUrl": "https://www.instagram.com/reel/DSMkv1pk_tm/",
    "notes": "Note rite: Maronite; Instagram active December 2025; no standalone website confirmed",
    "lat": 33.89,
    "lon": 35.5
  },
  {
    "id": "monika-bartosiak",
    "name": "Monika Bartosiak",
    "type": "Individual",
    "order": null,
    "city": "Warsaw",
    "region": "Masovian",
    "country": "Poland",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Iconoria studio Warsaw",
      "egg tempera and gold leaf traditional icons",
      "letter Catholic Register 2026 referencing active practice"
    ],
    "training": "Traditional iconography; egg tempera gold leaf",
    "endorser": "Polish Catholic communities",
    "activeSince": 2026,
    "sourceUrl": "https://www.catholicregister.org/item/746-iconography-from-darkness-to-light",
    "notes": "Name and studio Iconoria confirmed by letter to Catholic Register March 2026; no email or URL verified beyond mention",
    "lat": 52.23,
    "lon": 21.01
  },
  {
    "id": "oleh-skoropadsky",
    "name": "Oleh Skoropadsky",
    "type": "Individual",
    "order": null,
    "city": "Olympia",
    "region": "Washington",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Byzantine Iconography Workshop Olympia WA 2024 (co-instructor with Oleksii Cherednichenko)"
    ],
    "training": "Ukrainian Greek Catholic iconographic tradition",
    "endorser": "Ukrainian Greek Catholic communities",
    "activeSince": 2024,
    "sourceUrl": "https://www.tickettailor.com/events/vineyardofthelordcatholicministries/1370297",
    "notes": "Note rite: Ukrainian Greek Catholic; workshop confirmed 2024",
    "lat": 47.04,
    "lon": -122.89
  },
  {
    "id": "oleksii-cherednichenko",
    "name": "Oleksii Cherednichenko",
    "type": "Individual",
    "order": null,
    "city": "Olympia",
    "region": "Washington",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Byzantine Iconography Workshop Olympia WA 2024 (co-instructor with Oleh Skoropadsky)"
    ],
    "training": "Ukrainian Greek Catholic iconographic tradition",
    "endorser": "Ukrainian Greek Catholic communities",
    "activeSince": 2024,
    "sourceUrl": "https://www.tickettailor.com/events/vineyardofthelordcatholicministries/1370297",
    "notes": "Note rite: Ukrainian Greek Catholic; workshop confirmed 2024",
    "lat": 47.04,
    "lon": -122.89
  },
  {
    "id": "maria-guadalupe-levangie",
    "name": "Maria Guadalupe Levangie",
    "type": "Individual",
    "order": null,
    "city": "Campeche",
    "region": null,
    "country": "Mexico",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": "kalos@iconografia.mx",
    "notableWorks": [
      "Kalos Iconography retreats Mexico 2022–2024",
      "Canada 2024"
    ],
    "training": "Traditional iconography formation; Campeche Mexico",
    "endorser": "Archdiocese of Halifax-Yarmouth; Mexico parishes",
    "activeSince": 2024,
    "sourceUrl": "https://www.catholicregister.org/item/746-iconography-from-darkness-to-light",
    "notes": "Mexican iconographer; now co-directing Kalos with husband Dave Levangie from Halifax; email publicly listed per article",
    "lat": 19.84,
    "lon": -90.53
  },
  {
    "id": "michelle-arnold-paine",
    "name": "Michelle Arnold Paine",
    "type": "Individual",
    "order": null,
    "city": "Massachusetts",
    "region": "Massachusetts",
    "country": "USA",
    "disciplines": [
      "Panel painting",
      "Watercolor"
    ],
    "website": "https://michellepaine.com",
    "email": null,
    "social": "@michellearnoldpaine",
    "notableWorks": [
      "Norcia Basilica print fundraiser for monks",
      "liturgical panel paintings"
    ],
    "training": "Florence Academy of Art classical training",
    "endorser": "Monks of Norcia; Catholic patrons",
    "activeSince": 2021,
    "sourceUrl": "https://michellepaine.com/norcia/",
    "notes": "Classical figurative oil painter; also does non-sacred work; active 2021–confirmed",
    "lat": 42.41,
    "lon": -71.38
  },
  {
    "id": "dmitri-andreyev",
    "name": "Dmitri Andreyev",
    "type": "Individual",
    "order": null,
    "city": "Brookfield",
    "region": "Vermont",
    "country": "USA",
    "disciplines": [
      "Iconography"
    ],
    "website": null,
    "email": null,
    "social": null,
    "notableWorks": [
      "Private and church commissions",
      "Prosopon School instructor since 1993"
    ],
    "training": "Prosopon School of Iconology; trained under Vladislav Andrejev (founder)",
    "endorser": "Multiple US parishes; Prosopon School",
    "activeSince": 2021,
    "sourceUrl": "https://www.linkedin.com/in/dmitri-andreyev-a69b7436",
    "notes": "Russian Orthodox background; takes Catholic commissions (Prosopon School serves both); note Orthodox affiliation",
    "lat": 44.04,
    "lon": -72.61
  }
];

export const DIRECTORY_COUNT = DIRECTORY_ENTRIES.length;

export const DIRECTORY_COUNTRIES = Array.from(
  new Set(DIRECTORY_ENTRIES.map((e) => e.country)),
).sort();

export const DIRECTORY_DISCIPLINES = Array.from(
  new Set(DIRECTORY_ENTRIES.flatMap((e) => e.disciplines)),
).sort();
